syntax = "proto3";

// Minimal wire-compatible subset of Android Emulator's controller protocol:
// https://android.googlesource.com/platform/prebuilts/android-emulator/+/refs/heads/main/linux-x86_64/lib/emulator_controller.proto

package android.emulation.control;

import "google/protobuf/empty.proto";

service EmulatorController {
  rpc injectAudio(stream AudioPacket) returns (google.protobuf.Empty);
}

message AudioFormat {
  enum SampleFormat {
    AUD_FMT_U8 = 0;
    AUD_FMT_S16 = 1;
  }
  enum Channels {
    Mono = 0;
    Stereo = 1;
  }
  enum DeliveryMode {
    MODE_UNSPECIFIED = 0;
    MODE_REAL_TIME = 1;
  }
  uint64 samplingRate = 1;
  Channels channels = 2;
  SampleFormat format = 3;
  DeliveryMode mode = 4;
}

message AudioPacket {
  AudioFormat format = 1;
  uint64 timestamp = 2;
  bytes audio = 3;
}
